---
# Ingress
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bms-ingress
  labels:
    app: bms
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host:   # replace with your domain OR remove host block to use path-only ingress
    http:
      paths:
      - path: /asha
        pathType: Prefix
        backend:
          service:
            name: bms-service
            port:
              number: 80
